apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-service-deployment
  labels:
    app: post-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: post-service
  template:
    metadata:
      labels:
        app: post-service
    spec:
      containers:
        - image: kifill1998/kevinifill:%TAG%
          imagePullPolicy: Always
          name: post-service
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: post-service-service
spec:
  selector:
    app: post-service
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
