apiVersion: apps/v1
kind: Deployment
metadata:
  name: reimburse-deployment
  labels:
    app: reimburse
spec:
  replicas: 2
  selector:
    matchLabels:
      app: reimburse
  template:
    metadata:
      labels:
        app: reimburse
    spec:
      containers:
        - image: ijayzo/proj1:%TAG%
          imagePullPolicy: Always
          name: reimburse
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: reimburse-service
spec:
  selector:
    app: reimburse
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
